#!/usr/bin/env bash
NCAMERA_FILE=$1
IMU_FILE=$2
WHEEL_FILE=$3
LOCALIZATION_MAP_INPUT=$4
LOCALIZATION_MAP_OUTPUT=$5
REST=$@

rosrun rovioli rovioli \
  --alsologtostderr=1 \
  --v=1 \
  --ncamera_calibration=$NCAMERA_FILE  \
  --imu_parameters_maplab=$IMU_FILE \
  --publish_debug_markers  \
  --datasource_type="rostopic" \
  --optimize_map_to_localization_map=false \
  --vio_localization_map_folder=$LOCALIZATION_MAP_INPUT \
  --map_builder_save_image_as_resources=false \
  --save_map_folder=$LOCALIZATION_MAP_OUTPUT \
  --wheel_parameters=$WHEEL_FILE \
  --use_wheel_odometry=true $REST
